# Generated by Django 5.1.3 on 2024-11-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_alter_owned_price_alter_recommended_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="owned",
            old_name="count",
            new_name="quantity",
        ),
        migrations.RenameField(
            model_name="recommended",
            old_name="count",
            new_name="quantity",
        ),
    ]
