# Generated by Django 5.1.3 on 2024-12-04 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_name_user_nickname_user_profile_image"),
        ("stock", "0003_rename_count_owned_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="owned",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recommended",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.user",
            ),
            preserve_default=False,
        ),
    ]
