# Generated by Django 5.1.3 on 2024-12-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_owned_customer_recommended_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="owned",
            old_name="customer",
            new_name="nickname",
        ),
        migrations.RenameField(
            model_name="owned",
            old_name="name",
            new_name="stock",
        ),
        migrations.RenameField(
            model_name="recommended",
            old_name="customer",
            new_name="nickname",
        ),
        migrations.RenameField(
            model_name="recommended",
            old_name="name",
            new_name="stock",
        ),
    ]
