# Generated by Django 5.1.3 on 2024-12-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_rename_nickname_owned_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommended',
            name='price',
        ),
        migrations.RemoveField(
            model_name='recommended',
            name='quantity',
        ),
    ]
