# Generated by Django 5.1.3 on 2024-12-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_remove_recommended_price_remove_recommended_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owned',
            old_name='name',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='recommended',
            old_name='name',
            new_name='code',
        ),
    ]
