# Generated by Django 5.1.3 on 2024-12-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCorrelation",
            fields=[
                (
                    "StockCode",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("RelatedStockCode", models.CharField(max_length=10)),
                ("Correlation", models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.RenameField(
            model_name="stock",
            old_name="name",
            new_name="StockName",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="id",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="price",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="quantity",
        ),
        migrations.AddField(
            model_name="stock",
            name="StockCode",
            field=models.CharField(
                default=1, max_length=10, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
